#!/bin/bash

source ~/source/repos/mtu/python_venv/bin/activate

process_id=$(head -n 1 "/home/robbyj1388/source/repos/mtu/process_id.txt")

# if id exist 
if [ -n "$process_id" ]; then
  # if stop arg is given then kill process_id
  if [ "$1" == "stop" ]; then 
    kill -KILL "$process_id"
    # Delete old process id
    echo -n "" > process_id.txt
    echo "VPN stopped!"
    exit 0
  fi

# if file doesn't exist or is empty
elif [ ! -s "$process_id" ]; then
  if [ "$1" == "stop" ]; then 
    echo "No vpn active"
    exit 0
  else # no vpn is running so start new session
    process_id=$(python3 ./vpn_handler.py | tail -n 1)
    echo "VPN started!, id = $process_id"
    echo "$process_id" > process_id.txt
  fi
fi

